In [78]:
import pandas as pd
df =  pd.read_csv("customer_shopping_behavior.csv")
df.head()
df.info()
df.describe(include='all')

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [79]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [80]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x : x.fillna(x.median()))
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [81]:

df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')

df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'}) 
print(df.columns)

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [82]:
# create a new column age_group
labels = ['young adult', 'adult','middle aged','Senior']
df['age_group'] = pd.qcut(df['age'],q=4 ,labels=labels)

In [83]:
df[['age','age_group']].head(10)

   age    age_group
0   55  middle aged
1   19  young adult
2   50  middle aged
3   21  young adult
4   45  middle aged
5   46  middle aged
6   63       Senior
7   27  young adult
8   26  young adult
9   57  middle aged

In [84]:
frequenct_mapping = {
    'Fortnightly':14,
    'Weekly':7,
    'Monthly':30,
    'Quarterly':90,
    'Bi-Weekly':14,
    'Annually':365,
    'Every 3 Months':90

}
df['frequency_of_purchases_days'] = df['frequency_of_purchases'].map(frequenct_mapping)
print(df[['frequency_of_purchases','frequency_of_purchases_days']].head(10))
print("\n")
print(df['frequency_of_purchases_days'].isnull().sum())

  frequency_of_purchases  frequency_of_purchases_days
0            Fortnightly                           14
1            Fortnightly                           14
2                 Weekly                            7
3                 Weekly                            7
4               Annually                          365
5                 Weekly                            7
6              Quarterly                           90
7                 Weekly                            7
8               Annually                          365
9              Quarterly                           90


0

In [ ]:
(df[['discount_applied','promo_code_used']]).head()
(df['discount_applied'] == df['promo_code_used']).all()
df = df.drop('promo_code_used',axis=1)

In [88]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases', 'age_group',
       'frequency_of_purchases_days'],
      dtype='str')

In [95]:
import mysql.connector
# Database connection details for XAMPP
db_host = "localhost"
db_user = "root"
db_password = ""
db_name = "customer" # Replace with your actual database name

try:
    conn = mysql.connector.connect(
        host=db_host,
        user=db_user,
        passwd=db_password,
        database=db_name
    )
    if conn.is_connected():
        print("Connection to MySQL DB successful")
except mysql.connector.Error as e:
    print(f"Error connecting to MySQL DB: {e}")

Connection to MySQL DB successful

In [ ]:
import sys
import subprocess

def install(package):
    subprocess.check_call([sys.executable, "-m", "pip", "install", package])

try:
    from sqlalchemy import create_engine
    import pymysql
    print("SQLAlchemy and PyMySQL are successfully imported!")
except ImportError:
    print("Modules not found. Installing sqlalchemy and pymysql...")
    install('sqlalchemy')
    install('pymysql')
    from sqlalchemy import create_engine
    import pymysql
    print("Successfully installed and imported modules!")

engine = create_engine('mysql+pymysql://root:@localhost/customer')
try:
    df.to_sql('customers', con=engine, if_exists='replace', index=False)
    print(f"Successfully sent {len(df)} rows to XAMPP!")
except Exception as e:
    print(f"Error: {e}")
    print("\nTIP: Make sure XAMPP is running and the database 'customer' exists in phpMyAdmin.")

In [ ]:
from sqlalchemy import create_engine
# Connection string for XAMPP (default: root, no password, localhost)
engine = create_engine('mysql+pymysql://root:@localhost/customer')

try:
    # Sending the dataframe to the 'customers' table in the 'customer' database
    df.to_sql('customers', con=engine, if_exists='replace', index=False)
    print(f"Successfully sent {len(df)} rows to XAMPP!")
except Exception as e:
    print(f"Error: {e}")
    print("\nTIP: Make sure XAMPP is running (Apache & MySQL) and the database 'customer' exists in phpMyAdmin.")